# Generated by Django 4.1.3 on 2022-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_restaurant_id_userfavorite_liked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(default='#', max_length=1200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.CharField(default='#', max_length=788),
        ),
    ]
